config/routes.rb
Rails.application.routes.draw do
  resources :apartment_requests
  resources :profiles
  get 'home' => 'home#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :register do
    get 'register'  => :new
    post 'register' => :create
  end

  resources :users
  
  resources :apartments do
    member do
      patch 'occupy'
      patch 'vacate'
    end
    resources :apartment_requests, only: [:create, :update, :destroy]
  end

  resources :cities do
    resources :neighborhoods
  end
 
  get "up" => "rails/health#show", as: :rails_health_check
  
  root "home#index"
end

app/models/city.rb
class City < ApplicationRecord
    has_many :apartments
    has_many :neighborhoods, dependent: :destroy
    validates :name, presence: true, uniqueness: true
end

app/controllers/cities_controller.rb
class CitiesController < PublicController
  before_action :set_city, only: %i[ show edit update destroy ]

  # GET /cities or /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1 or /cities/1.json
  def show
  end

  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities or /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to city_url(@city), notice: "City was successfully created." }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1 or /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to city_url(@city), notice: "City was successfully updated." }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1 or /cities/1.json
  def destroy
    @city.destroy!

    respond_to do |format|
      format.html { redirect_to cities_url, notice: "City was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def city_params
      params.require(:city).permit(:name, :state, :country)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/views/cities/_city.html.erb
<div id="<%= dom_id city %>">
  <h1>
    <%= city.name %>
  </h1>

  <h2>
    <%= city.state %>, <%= city.country %>
  </h2>


  <% if action_name != "show" %>
    <%= link_to "Show this city", city, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this city", edit_city_path(city), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/cities/_form.html.erb
<%= form_with(model: city, class: "contents") do |form| %>
  <% if city.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(city.errors.count, "error") %> prohibited this city from being saved:</h2>

      <ul>
        <% city.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :state %>
    <%= form.text_field :state, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :country %>
    <%= form.text_field :country, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/cities/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing city</h1>

  <%= render "form", city: @city %>

  <%= link_to "Show this city", @city, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to cities", cities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cities/index.html.erb
<div class="w-full">
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Cities</h1>
    <%= link_to "New city", new_city_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>
  <div id="cities" class="min-w-full">
    <ul>
    <% @cities.each do |city| %>
      <li>
        <%= link_to city.name, city_path(city) %>
      </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/cities/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New city</h1>
  
  <%= render "form", city: @city %>

  <%= link_to "Back to cities", cities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/cities/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @city %>
    <hr></hr>
    <div> 
      <%= link_to "Add new neighborhood", new_city_neighborhood_path(@city), class: "text-white block font-medium button-small float-right" %>
    </div>
    <h3>
      Neighborhoods
    </h3>
    <ul>
    <% @city.neighborhoods.each do |neighborhood| %>
      <li>
        <%= link_to neighborhood.name, city_neighborhood_path(@city, neighborhood) %>
      </li>
      <% end %>
    </ul>

    <table>
    <thead>
      <tr>
        <th>Neighborhood</th>
        <th>Address</th>
        <th>Bedrooms</th>
        <th>Rent</th>
        <th>Remaining Bedrooms</th>
      </tr>
    </thead>
    <tbody>
      <% @city.apartments.each do |apartment| %>
          <tr>
            <td><%= apartment.neighborhood.name %></td>
            <td><%= link_to(apartment.street_address, apartment_path(apartment.id)) %></td>
            <td><%= apartment.bedrooms %></td>
            <td><%= number_to_currency(apartment.rent, precision: 0) %></td>
            <td><%= apartment.remaining_bedrooms %></td>
          </tr>
        <% end %>
    </tbody>
  </table>

    <%= link_to "Edit this city", edit_city_path(@city), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this city", city_path(@city), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to cities", cities_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>