config/routes.rb
Rails.application.routes.draw do
  resources :apartment_requests
  resources :profiles
  get 'home' => 'home#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :register do
    get 'register'  => :new
    post 'register' => :create
  end

  resources :users
  
  resources :apartments do
    member do
      patch 'occupy'
      patch 'vacate'
    end
    resources :apartment_requests, only: [:create, :update, :destroy]
  end

  resources :cities do
    resources :neighborhoods
  end
 
  get "up" => "rails/health#show", as: :rails_health_check
  
  root "home#index"
end

app/models/apartment.rb
class Apartment < ApplicationRecord
  belongs_to :neighborhood
  belongs_to :city
  has_many :residents, class_name: "User"
  has_many :apartment_requests, dependent: :destroy
  has_many :applicants, through: :apartment_requests, source: :applicant

  validates :street_address, presence: true
  validates :rent, presence: true, numericality: { greater_than_or_equal_to: 100 }
  validates :bedrooms, presence: true, numericality: { greater_than_or_equal_to: 1 }

  def remaining_bedrooms
    return bedrooms - residents.count
  end

  def unoccupied?
    if residents.count == 0
      return true
   else
      return false
   end
  end

  def current_resident?(user)
    if user.apartment_id == id 
      return true
    else 
      return false
    end
  end

  def request(user)
    user.apartment_requests.where(apartment_id: self.id).first
  end
  
  def requested?(user)
    request(user).present?
  end

  def request_pending?(user)
    request(user)&.pending?
  end
end

app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: %i[ show edit update destroy occupy vacate ]
  before_action :set_form_values, only: %i[new edit create update occupy vacate ]

  # GET /apartments or /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1 or /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments or /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        current_user.apartment_id = @apartment.id
        current_user.save
        format.html { redirect_to apartment_url(@apartment), notice: "Apartment was successfully created." }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1 or /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to apartment_url(@apartment), notice: "Apartment was successfully updated." }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1 or /apartments/1.json
  def destroy
    @apartment.destroy!

    respond_to do |format|
      format.html { redirect_to apartments_url, notice: "Apartment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def occupy 
    current_user.apartment_id = @apartment.id
    
    respond_to do |format|
      if current_user.save
        format.html { redirect_to apartment_url(@apartment), notice: "You have moved in!" }
      else
        format.html { render :show, status: :unprocessable_entity }
      end
    end
  end

  def vacate
    current_user.apartment_id = nil
    
    respond_to do |format|
      if current_user.save
        if @apartment.residents.count == 0
          @apartment.destroy
        end
        format.html { redirect_to apartments_url, notice: "You have moved out!" }
      else
        format.html { render :show, status: :unprocessable_entity }
      end
    end
  end

  def set_form_values
    @cities = City.all
    @neighborhoods = Neighborhood.all
  end

  def pending_requests
    @pending_applications = @apartment.apartment_requests.where(status: :pending).includes(:applicant => :profile)
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def apartment_params
      params.require(:apartment).permit(:street_address, :bedrooms, :rent, :notes, :neighborhood_id, :city_id)
    end
end

app/helpers/apartments_helper.rb
module ApartmentsHelper
end

app/views/apartments/_apartment.html.erb
<div id="<%= dom_id apartment %>">
  <div id="message-popup" class="hidden message-popup p-6 bg-white shadow-md rounded-md">
    <h1 class="text-4xl font-semibold mb-4">
      Please enter a message to 
      <% apartment.residents.each_with_index do |resident, index| %>
        <% if apartment.residents.count == 1 || index < apartment.residents.count - 1 %>
          <%= resident.profile.name %>
        <% else %>
          and <%= resident.profile.name %>
        <% end %>
      <% end %>

    </h1>
    <div class="w-full">
      <% req = ApartmentRequest.new() %>
      <%= form_with(model: req, class: "space-y-4 w-full") do |form| %>
        <%= form.label :message, class: "hidden" %>
        <%= form.text_area :message, class: "w-full h-40 shadow rounded-md border border-gray-300 outline-none px-3 py-2 mt-1 resize-none" %>
        <%= form.hidden_field :apartment_id, value: apartment.id %>
        <div class="flex justify-center space-x-4">
          <%= form.submit "Send Message", class: "py-3 px-5 bg-blue-600 text-white font-medium rounded-lg cursor-pointer" %>
        </div>
      <% end %>
    </div>

    <div class="flex justify-center space-x-4 w-full">
      <button class="py-3 px-5 bg-gray-100 text-gray-800 font-medium rounded-lg cursor-pointer" id="back-button">Back</button>
    </div>
  </div>
  <h2>
  <%= link_to apartment.city.name, city_path(apartment.city) %>
  </h2>
  <h3>
    <%= apartment.neighborhood.name %>
  </h3>
  <h1>
    <%= apartment.street_address %>
  </h1>

  <p class="my-5">
    <strong class="block font-medium mb-1 inline-block">Bedrooms:</strong> <%= apartment.bedrooms %> 
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1 inline-block">Rent:</strong>
    <%= apartment.rent %>
  </p>

  <p class="my-5">
    <%= apartment.notes %>
  </p>

  <div class="bg-gray-300 p-4">
    
    <h3>
      <%= apartment.residents.count %> Residents
    </h3>

    <ul>
      <% apartment.residents.each do |resident| %>
        <li> 
          <%= roommate_display(resident.profile) %>
        </li>
      <% end %>
    </ul>


    <% if apartment.current_resident?(current_user) %>
      <%= button_to("Move Out", vacate_apartment_path(apartment), method: :patch, class: "button-small bg-red-600") %>
    <% elsif apartment.unoccupied? %>
      <%= button_to("Move In", occupy_apartment_path(apartment), method: :patch, class: "button-small bg-green-600") %>
    <% elsif apartment.residents.count >= apartment.bedrooms %>
      <h3 class="text-red-500">
        This Apartment is Currently Full
      </h3>
    <% else %>
      <h3>
        <%= apartment.apartment_requests.pending.count %> Applicants
      </h3>

      <ul>
        <% apartment.applicants.each do |applicant| %>
          <% if apartment.request_pending?(applicant) %>
            <li> 
              <%= roommate_display(applicant.profile) %>
            </li>
          <% end %>
        <% end %>
      </ul>
      <%if apartment.requested?(current_user)%>
        <%= button_to("Unapply", apartment_apartment_request_path(apartment, apartment.request(current_user)), method: :delete, class: "button-small bg-red-600") %>
      <%elsif (apartment.residents.count < apartment.bedrooms)%>
        <button class= "button-small bg-green-600", id="apply-button">Apply</button>
      <%else%>
      <%end%>
    <% end %>
  </div>

  <% if action_name != "show" %>
    <%= link_to "Show this apartment", apartment, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this apartment", edit_apartment_path(apartment), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/apartments/_form.html.erb
<%= form_with(model: apartment, class: "contents") do |form| %>
  <% if apartment.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(apartment.errors.count, "error") %> prohibited this apartment from being saved:</h2>

      <ul>
        <% apartment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :street_address %>
    <%= form.text_field :street_address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :bedrooms %>
    <%= form.number_field :bedrooms, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :rent %>
    <%= form.text_field :rent, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :notes %>
    <%= form.text_area :notes, rows: 4, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

    <div class="my-5">
      <%= form.label :neighborhood_id %>
      <%= form.collection_select :neighborhood_id, @neighborhoods, :id, :name, prompt: true %>
      
      <%= form.label :city_id %>
      <%= form.collection_select :city_id, @cities, :id, :name, prompt: true %>
    </div>
  
  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/apartments/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing apartment</h1>

  <%= render "form", apartment: @apartment %>

  <%= link_to "Show this apartment", @apartment, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to apartments", apartments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/apartments/index.html.erb
<div class="w-full">
  
  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Apartments</h1>
    <%= link_to "Add your Apartment", new_apartment_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="apartments" class="min-w-full">
    <%= render @apartments %>
  </div>

  
</div>

app/views/apartments/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New apartment</h1>

  <%= render "form", apartment: @apartment %>

  <%= link_to "Back to apartments", apartments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/apartments/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <%= render @apartment %>

    <%= link_to "Edit this apartment", edit_apartment_path(@apartment), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this apartment", apartment_path(@apartment), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to apartments", apartments_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>