config/routes.rb
Rails.application.routes.draw do
  resources :apartment_requests
  resources :profiles
  get 'home' => 'home#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  controller :register do
    get 'register'  => :new
    post 'register' => :create
  end

  resources :users
  
  resources :apartments do
    member do
      patch 'occupy'
      patch 'vacate'
    end
    resources :apartment_requests, only: [:create, :update, :destroy]
  end

  resources :cities do
    resources :neighborhoods
  end
 
  get "up" => "rails/health#show", as: :rails_health_check
  
  root "home#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RoommaticPc244</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'applyMessage', 'data-turbolinks-track': 'reload' %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="bg-white shadow-lg">
    <div class="flex justify-between items-center">
      <div class="flex space-x-4">
        <%= link_to 'Home', home_path, class: "inline-block border border-white rounded hover:border-gray-200 text-blue-500 hover:bg-gray-200 py-1 px-3" %>
        <%= link_to 'Cities', cities_path, class: "inline-block border border-white rounded hover:border-gray-200 text-blue-500 hover:bg-gray-200 py-1 px-3" %>
        <%= link_to 'Apartments', apartments_path, class: "inline-block border border-white rounded hover:border-gray-200 text-blue-500 hover:bg-gray-200 py-1 px-3" %>
      </div>
        <div class="flex space-x-4">
          <% if @current_user %>
            <%= link_to @current_user.email, profile_path(@current_user.id), class: "inline-block border border-white rounded hover:border-gray-200 text-blue-500 hover:bg-gray-200 py-1 px-3" %>
            <%= button_to 'Logout', logout_path, method: :delete, class: "inline-block border border-white rounded hover:border-gray-200 text-blue-500 hover:bg-gray-200 py-1 px-3" %>
          <% else %>
            <%= link_to 'Login', login_path, class: "inline-block border border-white rounded hover:border-gray-200 text-blue-500 hover:bg-gray-200 py-1 px-3" %>
          <% end %>
        </div>
      </div>
    </nav>
    <div class="w-full mx-20 my-3">
      <% if (notice.present?) || (alert.present?) %>
        <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
      <% end %>
    </div>
    <main class="container mx-auto mt-8 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>